services:
  - type: web
    name: parkway-backend
    env: node
    plan: starter
    buildCommand: npm run build-all
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://aqjjgmmvviozmedjgxdy.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxampnbW12dmlvem1lZGpneGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMjA5MTUsImV4cCI6MjA3Njg5NjkxNX0.XCQQfVAGDTnDqC4W6RHMd8Rmj3C8UyFUmE-S18JVLWk
      - key: STRIPE_SECRET_KEY
        value: your_stripe_secret_key_here
      - key: CLOUDINARY_CLOUD_NAME
        value: your_cloudinary_cloud_name_here
      - key: CLOUDINARY_API_KEY
        value: your_cloudinary_api_key_here
      - key: CLOUDINARY_API_SECRET
        value: your_cloudinary_api_secret_here
    healthCheckPath: /health
    autoDeploy: true